version: "3.6"  

services: 
  orchestrator: 
    build: ./orchestrator 
    ports: 
      - "80:4000" 
    environment: 
      REDIS_PASSWORD: ${REDIS_PASSWORD} 
      BASE_URL_APP: http://app:4002
      BASE_URL_USER: http://users:4001
  users: 
    build: ./services/users 
    ports: 
      - "6001:4001" 
    environment: 
      MONGODB: ${MONGODB} 
  app: 
    build: ./services/app 
    ports:
      - "6002:4002" 
    environment: 
      DATABASE_URL: ${DATABASE_URL}